### PR TITLE
feat: Allow to configure firstDayOfWeek

### PR DESCRIPTION
**Pull request by biko8**
I'm creating website for Spain, and in spain the thay of the week is monday.

Changes on this PR are to allow users to configure firstDayOfWeek.

### CODE REVIEW

**Comment by aboveyunhai** [comment]
@biko8 nice work! let me check if there is a more dynamic way to tick the offset so you don't need to pass your own `weekday_name` with a different order.

**Comment by aboveyunhai** [comment]
now you should be able to do the following without all the configs
```
       configs={{
            firstDayOfWeek: 1,
          }}
```

**Comment by aboveyunhai** [comment]
npm@0.2.4 is out.

**Comment by biko8** [comment]
Nice work! Thank you!

**Pull request merged**
